

// Tipos de acciones
export const ACTION_TYPES = {
  SET_POKEMONS: 'SET_POKEMONS',
  CATCH_POKEMON: 'CATCH_POKEMON',
  RELEASE_POKEMON: 'RELEASE_POKEMON',
  SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
  SET_LOADING: 'SET_LOADING',
  SET_ERROR : 'SET_ERROR'
};